// Pre-recorded apology clips for extension.rate_limited (generated by
// scripts/generate_apology_clips.py). Local audio on purpose: the realtime
// model is the thing that is rate-limited, so it cannot say it.
export const APOLOGY_LANGUAGES = ["en", "es", "fr", "ja"] as const;

export type ApologyLanguage = (typeof APOLOGY_LANGUAGES)[number];

export function apologyLanguage(language: string | undefined | null): ApologyLanguage {
    const base = (language || "").toLowerCase().split(/[-_]/)[0];
    return (APOLOGY_LANGUAGES as readonly string[]).includes(base) ? (base as ApologyLanguage) : "en";
}

export function apologyClipUrl(language: string | undefined | null): string {
    return `/audio/rate-limit-apology-${apologyLanguage(language)}.wav`;
}
